---
kind: Service
apiVersion: v1
metadata:
  annotations:
    description: The PetID Vue SPA web server's http port.
  labels:
    app: pet-id-frontend
    app.kubernetes.io/name: pet-id-frontend
    app.kubernetes.io/part-of: pet-id
    component: pet-id-frontend-service
  name: pet-id-frontend
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    deployment: pet-id-frontend
  type: ClusterIP