---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: pet-id-frontend
  labels:
    app: pet-id-frontend
    app.kubernetes.io/part-of: pet-id-frontend
    component: pet-id-frontend-route
spec:
  to:
    kind: Service
    name: pet-id-frontend
    weight: 100
  port:
    targetPort: pet-id-frontend
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None