---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: petadoption-db-claim
  labels:
    app: furever-home-process-adoptee-usvc
    app.kubernetes.io/name: furever-home-process-adoptee-usvc
    app.kubernetes.io/part-of: furever-home-process-adoptee-usvc
    component: pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi