apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: new-adoptees
  labels:
    strimzi.io/cluster: pet-cluster
spec:
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
  partitions: 10
  replicas: 3