apiVersion: v1
kind: ConfigMap
metadata:
  name: pet-id-backend-env
  labels:
    app: pet-id-backend
    app.kubernetes.io/name: pet-id-backend
    app.kubernetes.io/part-of: pet-id-backend
    component: configmap
data:
  .env: |
    app:
      server:
        host: 0.0.0.0
        base_path: "/app"
        port: 8080
        timeout:
          server: 30
          read: 15
          write: 10
          idle: 5

      db_connection:
        server: localhost
        port: 3306
        username: petiddbu
        password: securePassword
        database: petid

      config:
        three_scale_header_secret: someSecret_value_for_a_shared_secret