apiVersion: apps/v1
kind: Deployment
metadata:
  name: pet-id-backend
  labels:
    app: pet-id
    app.kubernetes.io/part-of: pet-id
    component: deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pet-id-backend
  template:
    metadata:
      labels:
        app: pet-id-backend
    spec:
      containers:
      - name: pet-id-backend
        image: quay.io/kenmoini/pet-id-backend:latest
        ports:
        - containerPort: 8080
          name: pet-id-backend
        env:
          - name: KEYCLOAK_SERVER
            value: http://rh-sso:8080/auth
          - name: KEYCLOAK_REALM
            value: someRealm
          - name: KEYCLOAK_CLIENT_ID
            value: someClientID
          - name: THREE_SCALE_SECRET_HEADER
            value: someSecretHeaderKeyValue