---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: rh-3scale-postgresql
  labels:
    app: db-services
    app.kubernetes.io/part-of: db-services
    component: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-services
      component: database
  template:
    metadata:
      name: rh-3scale-postgresql
      creationTimestamp: null
      labels:
        app: db-services
        component: database
    spec:
      volumes:
        - name: rh-3scale-postgresql-claim
          persistentVolumeClaim:
            claimName: rh-3scale-postgresql-claim
      containers:
        - resources: {}
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - '-c'
                - >-
                  psql -h 127.0.0.1 -U $POSTGRESQL_USER -q -d
                  $POSTGRESQL_DATABASE -c 'SELECT 1'
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          name: rh-3scale-postgresql
          livenessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: rh-3scale-db-secret
                  key: POSTGRES_USERNAME
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rh-3scale-db-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRESQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: rh-3scale-db-secret
                  key: POSTGRES_DATABASE
          ports:
            - containerPort: 5432
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: rh-3scale-postgresql-claim
              mountPath: /var/lib/pgsql/data
          terminationMessagePolicy: File
          image: 'registry.redhat.io/rhel8/postgresql-10:1'
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  strategy:
    type: Recreate
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600