---
kind: Secret
apiVersion: v1
metadata:
  name: rh-3scale-db-secret
  labels:
    app: db-services
    app.kubernetes.io/part-of: db-services
    component: database
stringData:
  POSTGRES_DATABASE: "3scale"
  POSTGRES_HOST: "rh-3scale-postgresql"
  POSTGRES_PASSWORD: "someSuperSecretP455"
  POSTGRES_USERNAME: "3scale"
  POSTGRES_VERSION: "10"
type: Opaque