---
kind: Service
apiVersion: v1
metadata:
  name: rh-3scale-zync-postgresql
  labels:
    app: db-services
    app.kubernetes.io/part-of: db-services
    component: zync-service
spec:
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: rh-3scale-zync-postgresql
    component: zync-database
  type: ClusterIP