kind: Secret
apiVersion: v1
metadata:
  name: rh-3scale-zync-db-secret
  labels:
    app: db-services
    app.kubernetes.io/part-of: db-services
    component: zync-secret
stringData:
  POSTGRES_DATABASE: "zync"
  POSTGRES_HOST: "rh-3scale-zync-postgresql"
  POSTGRES_PASSWORD: "someSuperSecretP455"
  POSTGRES_USERNAME: "zync"
  POSTGRES_VERSION: "10"
type: Opaque