---
kind: Service
apiVersion: v1
metadata:
  name: rh-sso-discovery
  labels:
    app: rh-sso
    app.kubernetes.io/part-of: rh-sso
    component: service
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: rh-sso
    component: rh-sso
  type: ClusterIP