---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rh-sso-postgresql-claim
  namespace: rh-sso-demo
  labels:
    app: rh-sso
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi