apiVersion: apps/v1
kind: Deployment
metadata:
  name: process-adoptee-usvc
  labels:
    app: furever-home
    app.kubernetes.io/name: process-adoptee-usvc
    app.kubernetes.io/part-of: furever-home
    component: deployment
  annotations:
    app.openshift.io/connects-to: >-
      [{"apiVersion":"apps.openshift.io/v1","kind":"DeploymentConfig","name":"petadoption-db"},{"apiVersion":"apps/v1","kind":"StatefulSet","name":"pet-cluster-kafka"}]
spec:
  replicas: 1
  selector:
    matchLabels:
      app: process-adoptee-usvc
  template:
    metadata:
      labels:
        app: process-adoptee-usvc
    spec:
      containers:
      - name: process-adoptee-usvc
        imagePullPolicy: Always
        image: quay.io/kenmoini/furever-home-process-adoptee-usvc:latest
        env:
          - name: CYCLE_SECONDS
            value: "30"
          - name: KAFKA_CLUSTER_ENDPOINT
            value: 'pet-cluster-kafka-bootstrap:9092'
          - name: KAFKA_TOPIC
            value: new-adoptees
          - name: KAFKA_GROUP_ID
            value: process-pet-group
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                key: database-user
                name: petadoption-db
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                key: database-password
                name: petadoption-db
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                key: database-name
                name: petadoption-db
          - name: DB_DB
            valueFrom:
              secretKeyRef:
                key: database-name
                name: petadoption-db