apiVersion: v1
kind: ConfigMap
metadata:
  name: furever-home-frontend-js-overrides
  labels:
    app: furever-home-frontend
    app.kubernetes.io/name: furever-home-frontend
    app.kubernetes.io/part-of: furever-home-frontend
    component: configmap
data:
  overrides.js: |
    var API_ENDPOINT = "https://furever-home-backend-a-rh-sso-demo.apps.core-ocp.kemo.labs";
    var JUDGE_ENDPOINT = "https://furever-home-adoption-judge-usvc-a-rh-sso-demo.apps.core-ocp.kemo.labs";
    var USER_ID = 1;
  functions.js: |
    console.log('hello from the functions file!');
  keycloak-shared.js: |
    function initKeycloak() {
      var keycloak = new Keycloak({
        url: '',
        realm: '',
        clientId: ''
      });
      keycloak.init().then(function(authenticated) {
        if (authenticated) {
          username = keycloak.subject;
          token = keycloak.token;
          jQuery(".text-username").text(username);
        }
        alert(authenticated ? 'authenticated' : 'not authenticated');
      }).catch(function() {
        alert('failed to initialize');
      });
    }