apiVersion: v1
kind: ConfigMap
metadata:
  name: pet-id-backend-config-yml
  labels:
    app: pet-id-backend
    app.kubernetes.io/name: pet-id-backend-config-yml
    app.kubernetes.io/part-of: pet-id
    component: configmap
data:
  config.yml: |
    app:
      server:
        host: 0.0.0.0
        base_path: "/app"
        port: 8080
        timeout:
          server: 30
          read: 15
          write: 10
          idle: 5

      db_connection:
        server: petid-db
        port: 3306
        username: petid
        password: petid
        database: petid

      config:
        three_scale_header_secret: someSecret_value_for_a_shared_secret