apiVersion: apps/v1
kind: Deployment
metadata:
  name: add-adoptee-usvc
  annotations:
    app.openshift.io/connects-to: '[{"apiVersion":"apps/v1","kind":"StatefulSet","name":"pet-cluster-kafka"}]'
  labels:
    app: add-adoptee-usvc
    app.kubernetes.io/name: add-adoptee-usvc
    app.kubernetes.io/part-of: furever-home
    component: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: add-adoptee-usvc
  template:
    metadata:
      labels:
        app: add-adoptee-usvc
    spec:
      containers:
      - name: add-adoptee-usvc
        imagePullPolicy: Always
        image: quay.io/kenmoini/furever-home-add-adoptee-usvc:latest
        env:
          - name: CYCLE_SECONDS
            value: "30"
          - name: KAFKA_CLUSTER_ENDPOINT
            value: 'pet-cluster-kafka-bootstrap:9092'
          - name: KAFKA_TOPIC
            value: new-adoptees