# Build the manager binary
FROM quay.io/polyglotsystems/golang-ubi:latest as builder

WORKDIR /workspace

COPY . .

RUN go mod download

# Build
RUN make build

# Use distroless as minimal base image to package the manager binary
# Refer to https://github.com/GoogleContainerTools/distroless for more details
FROM registry.access.redhat.com/ubi8/ubi-minimal:8.3

WORKDIR /

COPY --from=builder /workspace/dist/pet-id .

USER root

RUN mkdir -p /opt/app-root \
 && chmod -R 777 /opt/app-root
 && chown -R 65532:65532 /opt/app-root

USER 65532:65532

ENTRYPOINT ["/pet-id -config /opt/app-root/config.yml"]