FROM quay.io/polyglotsystems/ubi8-nginx:latest as BUILDER

USER root

COPY app/ /var/www/html/

RUN npm i \
 && npm run css-compile \
 && npx webpack

USER 1001

FROM registry.access.redhat.com/ubi8/httpd-24:latest

COPY --from=BUILDER /var/www/html/ /var/www/html/