FROM quay.io/polyglotsystems/ubi8-nginx:latest

ENV APP_NAME go-nodejs-pet-id
ENV APP_VERSION 2

USER root

#WORKDIR "/opt/app-root/src"
WORKDIR "/var/www/html"

COPY container-root/ /

COPY . /var/www/html


RUN npm install \
 && npm run build \
 && chown -R 1001:1001 . \
 && chmod -R 777 .

USER 1001

EXPOSE 8080

#FROM registry.access.redhat.com/ubi8/httpd-24:latest
#
#COPY --from=builder /opt/app-root/src/dist/ /var/www/html/dist/
#COPY --from=builder /opt/app-root/src/index.html /var/www/html/index.html
#COPY silent-sso-check.html /var/www/html/silent-sso-check.html