---
- name: Deploy full RH SSO Demo to OpenShift
  hosts: localhost
  connection: local

  vars:
    deploy_sso: true
    deploy_3scale: true
    deploy_serverless: true
    deploy_kafka: true
    deploy_kong: false
    deploy_apps: true

    service_ns: a-rh-sso-demo
    app_ns: a-sso-app-demo

  tasks:

    - name: get route subdomain
      k8s_info:
        kind: IngressController
        name: default
        namespace: openshift-ingress-operator
      register: route_subdomain_r

    - name: set route_subdomain
      set_fact:
        route_subdomain: "{{ route_subdomain_r.resources[0].status.domain }}"

    - name: Create Namespace/Projects
      k8s:
        state: present
        kind: Namespace
        api_version: v1
        merge_type:
        - strategic-merge
        - merge
        definition:
          metadata:
            name: "{{ ns_item }}"
          spec: {}
      loop:
        - "{{ service_ns }}"
        - "{{ app_ns }}"
      loop_control:
        loop_var: ns_item

    - name: Deploy non-dependant Operators to cluster
      k8s:
        state: present
        definition: "{{ lookup('file', file_item ) | from_yaml }}"
      loop:
      - "../deploy-rh-serverless/step1/01-namespace-eventing.yaml"
      - "../deploy-rh-serverless/step1/01-namespace-serverless.yaml"
      - "../deploy-rh-serverless/step1/01-namespace-serving.yaml"
      - "../deploy-rh-serverless/step1/02-subscription.yaml"
      - "../deploy-rh-serverless/step1/03-operatorgroup.yaml"
      - "../deploy-rh-amq-streams/01-subscription.yaml"
      loop_control:
        loop_var: file_item

    - name: Deploy Red Hat SSO & other non-dependant services to {{ service_ns }}
      k8s:
        state: present
        namespace: "{{ service_ns }}"
        definition: "{{ lookup('file', file_item ) | from_yaml }}"
      loop:
      - "../deploy-rh-sso/02-service-rh-sso.yaml"
      - "../deploy-rh-sso/03-service-rh-sso-discovery.yaml"
      - "../deploy-rh-sso/04-service-rh-sso-monitoring.yaml"
      - "../deploy-rh-sso/05-service-rh-sso-postgresql.yaml"
      - "../deploy-rh-sso/06-route-rh-sso.yaml"
      - "../deploy-rh-sso/07-route-rh-sso-metrics-rewrite.yaml"
      - "../deploy-rh-sso/08-route-rh-sso-myrealm-metrics-rewrite.yaml"
      - "../deploy-rh-sso/09-secret-credential-rh-sso.yaml"
      - "../deploy-rh-sso/10-secret-rh-sso-db-secret.yaml"
      - "../deploy-rh-sso/11-configmap-rh-sso-probes.yaml"
      - "../deploy-rh-sso/12-pvc-rh-sso-postgresql-claim.yaml"
      - "../deploy-rh-sso/13-statefulset-rh-sso-postgresql.yaml"
      - "../deploy-rh-sso/14-statefulset-rh-sso.yaml"
      - "../deploy-rh-3scale/operator/step1/02-subscription.yaml"
      - "../deploy-rh-3scale/operator/step1/03-operatorgroup.yaml"
      loop_control:
        loop_var: file_item

    - name: Deploy non-dependant applications to {{ app_ns }}
      k8s:
        state: present
        namespace: "{{ app_ns }}"
        definition: "{{ lookup('file', file_item ) | from_yaml }}"
      loop:
      - "../services/python-staticjs-furever-home/static-frontend/openshift/00-configmap.yaml"
      - "../services/python-staticjs-furever-home/static-frontend/openshift/01-deployment.yaml"
      - "../services/python-staticjs-furever-home/static-frontend/openshift/02-service.yaml"
      - "../services/python-staticjs-furever-home/static-frontend/openshift/03-route.yaml"
      - "../services/python-staticjs-furever-home/python-process-adoptee-usvc/openshift/database/01-template-instance.yaml"
      - "../services/python-staticjs-furever-home/python-add-adoptee-usvc/openshift/kafka-instance/01-kafka-cluster.yaml"
      - "../services/python-staticjs-furever-home/python-adoption-judge-usvc/openshift/01-deployment.yaml"
      - "../services/python-staticjs-furever-home/python-adoption-judge-usvc/openshift/02-service.yaml"
      - "../services/python-staticjs-furever-home/python-adoption-judge-usvc/openshift/03-route.yaml"
      loop_control:
        loop_var: file_item

    - name: Wait for knative-serving CRD
      k8s_info:
        api_version: apiextensions.k8s.io/v1beta1
        kind: CustomResourceDefinition
        name: knativeservings.operator.knative.dev
      register: r_knserving_crd
      retries: 200
      delay: 10
      until: r_knserving_crd.resources | list | length == 1
      ignore_errors: true

    - name: Deploy Serverless-dependant Operators to cluster
      k8s:
        state: present
        definition: "{{ lookup('file', file_item ) | from_yaml }}"
      loop:
      - "../deploy-rh-serverless/step2/04-knative-eventing.yaml"
      - "../deploy-rh-serverless/step2/04-knative-serving.yaml"
      - "../deploy-rh-amq-streams/02-knative_kafka_cr.yaml"
      loop_control:
        loop_var: file_item

    - name: Wait for 3Scale CRD
      k8s_info:
        api_version: apiextensions.k8s.io/v1beta1
        kind: CustomResourceDefinition
        name: apimanagers.apps.3scale.net
      register: r_knserving_crd
      retries: 200
      delay: 10
      until: r_knserving_crd.resources | list | length == 1
      ignore_errors: true

    - name: Deploy 3Scale-dependant Instance to {{ service_ns }}
      k8s:
        state: present
        namespace: "{{ service_ns }}"
        kind: APIManager
        api_version: apps.3scale.net/v1alpha1
        definition:
          metadata:
            name: demo-apimanager
          spec:
            wildcardDomain: "{{ route_subdomain }}"
